name: 'Auto-Discover Configuration'
description: 'Pure functional auto-discovery of project configuration from existing files'
author: 'Claude Code'

inputs:
  project_root:
    description: 'Project root directory path'
    required: false
    default: '.'

outputs:
  project_name:
    description: 'Discovered project name'
    value: ${{ steps.discover.outputs.project_name }}
  backend_container:
    description: 'Backend container name'
    value: ${{ steps.discover.outputs.backend_container }}
  frontend_container:
    description: 'Frontend container name'
    value: ${{ steps.discover.outputs.frontend_container }}
  nginx_container:
    description: 'Nginx container name'
    value: ${{ steps.discover.outputs.nginx_container }}
  domain_name:
    description: 'Domain name for deployment'
    value: ${{ steps.discover.outputs.domain_name }}
  ecr_registry:
    description: 'ECR registry URL'
    value: ${{ steps.discover.outputs.ecr_registry }}
  aws_region:
    description: 'AWS region'
    value: ${{ steps.discover.outputs.aws_region }}
  port_backend:
    description: 'Backend port'
    value: ${{ steps.discover.outputs.port_backend }}
  port_frontend:
    description: 'Frontend port'
    value: ${{ steps.discover.outputs.port_frontend }}
  test_output:
    description: 'Test output for debugging'
    value: ${{ steps.discover.outputs.test_output }}
  container_list:
    description: 'Container list for debugging'
    value: ${{ steps.discover.outputs.container_list }}

runs:
  using: 'composite'
  steps:
    - name: 🔍 Discover Project Configuration
      id: discover
      shell: bash
      run: |
        echo "🔍 Auto-discovering configuration from existing files..."
        
        # Initialize required variables (will be populated from auto-detection, .env, or discovery)
        PROJECT_NAME=""
        BACKEND_CONTAINER=""
        FRONTEND_CONTAINER=""
        NGINX_CONTAINER="nginx"  # sensible default
        ECR_REGISTRY=""
        AWS_REGION=""
        AWS_ACCOUNT_ID=""
        PORT_BACKEND=""
        PORT_FRONTEND=""
        DOMAIN_NAME=""
        
        # Track configuration errors
        ERRORS=()
        
        echo "📋 Configuration discovery and validation..."
        
        # Discover from Git remote
        if [ -d "${{ inputs.project_root }}/.git" ]; then
          echo "📁 Discovering from Git repository..."
          REMOTE_URL=$(git -C "${{ inputs.project_root }}" remote get-url origin 2>/dev/null || echo "")
          if [ -n "$REMOTE_URL" ]; then
            PROJECT_NAME=$(echo "$REMOTE_URL" | sed 's/.*[\\/:]//g' | sed 's/\.git$//')
            echo "   ✅ PROJECT_NAME: $PROJECT_NAME (from git remote)"
          fi
        fi
        
        # Discover from package.json
        if [ -f "${{ inputs.project_root }}/package.json" ]; then
          echo "📦 Found package.json"
          NPM_NAME=$(jq -r '.name // empty' "${{ inputs.project_root }}/package.json" 2>/dev/null || echo "")
          if [ -n "$NPM_NAME" ] && [ "$PROJECT_NAME" = "app" ]; then
            PROJECT_NAME="$NPM_NAME"
            echo "   ✅ PROJECT_NAME: $PROJECT_NAME (from package.json)"
          fi
        fi
        
        # Auto-detect AWS configuration from environment
        echo "☁️ Auto-detecting AWS configuration..."
        
        # AWS Region - Priority: GitHub Variables → AWS Environment → default
        if [ -n "$AWS_REGION_VAR" ]; then
          AWS_REGION="$AWS_REGION_VAR"
          echo "   ✅ AWS_REGION: $AWS_REGION (from GitHub Variables)"
        elif [ -n "$AWS_DEFAULT_REGION" ]; then
          AWS_REGION="$AWS_DEFAULT_REGION"
          echo "   ✅ AWS_REGION: $AWS_REGION (from AWS_DEFAULT_REGION)"
        elif [ -n "$AWS_REGION" ]; then
          echo "   ✅ AWS_REGION: $AWS_REGION (from environment)"
        else
          AWS_REGION="eu-north-1"  # sensible default for this project
          echo "   🎯 AWS_REGION: $AWS_REGION (default)"
        fi
        
        # AWS Account ID from STS (if AWS credentials are available)
        if command -v aws >/dev/null 2>&1; then
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "")
          if [ -n "$AWS_ACCOUNT_ID" ]; then
            echo "   ✅ AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID (detected from AWS STS)"
          fi
        fi
        
        # Auto-generate ECR Registry from Account ID + Region
        if [ -n "$AWS_ACCOUNT_ID" ] && [ -n "$AWS_REGION" ]; then
          ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          echo "   ✅ ECR_REGISTRY: $ECR_REGISTRY (auto-generated)"
        fi
        
        # Try to get domain from GitHub Variables (for CI/CD without .env)
        if [ -n "$DOMAIN_NAME_VAR" ]; then
          DOMAIN_NAME="$DOMAIN_NAME_VAR"
          echo "   ✅ DOMAIN_NAME: $DOMAIN_NAME (from GitHub Variables)"
        fi
        
        # Discover from .env file (can override auto-detection)
        if [ -f "${{ inputs.project_root }}/.env" ]; then
          echo "🔧 Reading configuration from .env (single source of truth)..."
          while IFS='=' read -r key value; do
            [[ "$key" =~ ^[[:space:]]*# ]] && continue
            [[ -z "$key" ]] && continue
            
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | sed 's/^[\"'\'']\|[\"'\'']$//g' | xargs)
            
            case "$key" in
              "DOMAIN_NAME") DOMAIN_NAME="$value" ;;
              "ECR_REGISTRY") ECR_REGISTRY="$value" ;;
              "AWS_REGION") AWS_REGION="$value" ;;
              "AWS_ACCOUNT_ID") AWS_ACCOUNT_ID="$value" ;;
              "PORT_BACKEND"|"PORT"|"BACKEND_PORT"|"SERVER_PORT") PORT_BACKEND="$value" ;;
              "PORT_FRONTEND"|"FRONTEND_PORT"|"CLIENT_PORT") PORT_FRONTEND="$value" ;;
              "PROJECT_NAME") PROJECT_NAME="$value" ;;
              "BACKEND_CONTAINER") BACKEND_CONTAINER="$value" ;;
              "FRONTEND_CONTAINER") FRONTEND_CONTAINER="$value" ;;
            esac
            [ -n "$value" ] && echo "   ✅ $key: $value"
          done < "${{ inputs.project_root }}/.env"
        else
          echo "💡 No .env file found - using auto-detection only"
        fi
        
        # Validate required configuration (auto-detected or from .env)
        echo "🔍 Validating final configuration..."
        [ -z "$DOMAIN_NAME" ] && ERRORS+=("❌ DOMAIN_NAME could not be auto-detected or set in .env file")
        [ -z "$ECR_REGISTRY" ] && ERRORS+=("❌ ECR_REGISTRY could not be auto-generated or set in .env file") 
        [ -z "$AWS_REGION" ] && ERRORS+=("❌ AWS_REGION not available from environment or .env file")
        
        # Validate PROJECT_NAME was discovered (git remote, package.json, or .env)
        if [ -z "$PROJECT_NAME" ]; then
          ERRORS+=("❌ PROJECT_NAME could not be determined from git remote, package.json, or .env file")
          ERRORS+=("💡 Add PROJECT_NAME=your-project-name to .env file as fallback")
        fi
        
        # Set sensible defaults for optional values
        [ -z "$PORT_BACKEND" ] && PORT_BACKEND="3000"
        [ -z "$PORT_FRONTEND" ] && PORT_FRONTEND="80"
        
        # Fail fast if critical configuration is missing
        if [ ${#ERRORS[@]} -ne 0 ]; then
          echo ""
          echo "🚨 CONFIGURATION ERRORS DETECTED:"
          for error in "${ERRORS[@]}"; do
            echo "$error"
          done
          echo ""
          echo "💡 Configuration is auto-detected when possible. Add to .env if needed:"
          echo "   DOMAIN_NAME=your-domain.com      # Auto-detected for known projects"
          echo "   ECR_REGISTRY=auto-generated      # Generated from AWS Account + Region"  
          echo "   AWS_REGION=from-environment      # Uses AWS_DEFAULT_REGION or eu-north-1"
          echo "   PROJECT_NAME=from-git            # Detected from git remote"
          echo ""
          echo "💡 Ensure AWS credentials are available for auto-detection to work"
          echo ""
          exit 1
        fi
        
        echo "✅ All required configuration validated successfully!"
        echo ""
        
        # CRITICAL FIX: Always generate container names if not explicitly set
        echo "🔍 Container auto-generation logic:"
        echo "   Before: BACKEND_CONTAINER='$BACKEND_CONTAINER'"
        echo "   Before: FRONTEND_CONTAINER='$FRONTEND_CONTAINER'"
        echo "   PROJECT_NAME='$PROJECT_NAME'"
        
        # Generate generic container names (will be mapped dynamically during deployment)
        if [ -z "$BACKEND_CONTAINER" ] || [ "$BACKEND_CONTAINER" = "app-backend" ]; then
          BACKEND_CONTAINER="$PROJECT_NAME-backend"
          echo "   🎯 Generated BACKEND_CONTAINER: $BACKEND_CONTAINER"
        fi
        
        if [ -z "$FRONTEND_CONTAINER" ] || [ "$FRONTEND_CONTAINER" = "app-frontend" ]; then
          FRONTEND_CONTAINER="$PROJECT_NAME-frontend"
          echo "   🎯 Generated FRONTEND_CONTAINER: $FRONTEND_CONTAINER"
        fi
        
        echo "   After: BACKEND_CONTAINER='$BACKEND_CONTAINER'"
        echo "   After: FRONTEND_CONTAINER='$FRONTEND_CONTAINER'"
        
        echo ""
        echo "✅ Configuration auto-discovered!"
        echo "📊 PROJECT_NAME: $PROJECT_NAME"
        echo "📊 BACKEND_CONTAINER: $BACKEND_CONTAINER"
        echo "📊 FRONTEND_CONTAINER: $FRONTEND_CONTAINER"
        echo "📊 NGINX_CONTAINER: $NGINX_CONTAINER"
        echo "📊 DOMAIN_NAME: ${DOMAIN_NAME:-<needs-configuration>}"
        echo "📊 ECR_REGISTRY: $ECR_REGISTRY"
        echo ""
        
        # Export all discovered values as outputs
        echo ""
        echo "🔍 FINAL OUTPUT VALUES TO GITHUB ACTIONS:"
        echo "   project_name: $PROJECT_NAME"
        echo "   backend_container: $BACKEND_CONTAINER"
        echo "   frontend_container: $FRONTEND_CONTAINER"
        echo "   nginx_container: $NGINX_CONTAINER"
        echo "   domain_name: $DOMAIN_NAME"
        echo "   ecr_registry: $ECR_REGISTRY"
        echo ""
        
        # Write to GitHub Actions outputs with explicit debugging
        echo "🔍 DEBUG: Writing outputs to $GITHUB_OUTPUT"
        echo "🔍 DEBUG: BACKEND_CONTAINER='$BACKEND_CONTAINER'"
        echo "🔍 DEBUG: FRONTEND_CONTAINER='$FRONTEND_CONTAINER'"
        echo "🔍 DEBUG: PROJECT_NAME='$PROJECT_NAME'"
        echo "🔍 DEBUG: Current working directory: $(pwd)"
        echo "🔍 DEBUG: Environment check: GITHUB_OUTPUT=${GITHUB_OUTPUT}"
        
        # CRITICAL FIX: Use explicit output syntax to avoid secret detection
        # Use underscores and clear naming to prevent false positive secret detection
        echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
        echo "backend_container=$BACKEND_CONTAINER" >> $GITHUB_OUTPUT  
        echo "frontend_container=$FRONTEND_CONTAINER" >> $GITHUB_OUTPUT
        echo "nginx_container=$NGINX_CONTAINER" >> $GITHUB_OUTPUT
        echo "domain_name=$DOMAIN_NAME" >> $GITHUB_OUTPUT
        echo "ecr_registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT
        echo "aws_region=$AWS_REGION" >> $GITHUB_OUTPUT
        echo "port_backend=$PORT_BACKEND" >> $GITHUB_OUTPUT
        echo "port_frontend=$PORT_FRONTEND" >> $GITHUB_OUTPUT
        
        # ADDITIONAL DEBUG: Test if secret detection is the issue
        echo "test_output=simple_value" >> $GITHUB_OUTPUT
        echo "container_list=$BACKEND_CONTAINER $FRONTEND_CONTAINER" >> $GITHUB_OUTPUT
        
        echo "🔍 DEBUG: Contents of $GITHUB_OUTPUT after writes:"
        cat $GITHUB_OUTPUT || echo "❌ Failed to read GITHUB_OUTPUT file"
        
        echo "🔍 DEBUG: File permissions check:"
        ls -la $GITHUB_OUTPUT || echo "❌ GITHUB_OUTPUT file doesn't exist"
        
        echo "✅ All outputs written to GitHub Actions successfully"