services:
  backend:
    build: ./backend
    ports:
      - "8081:3000"
    environment:
      - ENV=development
      - PORT=3000
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
      - ./backend/test:/app/test
    command: clojure -M:run
    networks:
      - ical-network
  
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/resources:/app/resources
    environment:
      - NODE_ENV=development
    networks:
      - ical-network

networks:
  ical-network:
    driver: bridge