version: '3.8'

services:
  backend:
    build: ./backend
    env_file: .env.${ENVIRONMENT}
    networks:
      - platform
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    networks:
      - platform
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      backend:
        condition: service_healthy

networks:
  platform:
    external: true
