version: '3.8'

services:
  backend:
    image: ghcr.io/duersjefen/filter-ical-backend:latest
    container_name: filter-ical-backend-staging
    restart: unless-stopped
    ports:
      - "3001:3000"  # Staging on port 3001
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PASSWORD_ENCRYPTION_KEY=${PASSWORD_ENCRYPTION_KEY}
      - ENVIRONMENT=staging
    volumes:
      - websites-filter-ical-staging-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - filter-ical-staging

  frontend:
    image: ghcr.io/duersjefen/filter-ical-frontend:latest
    container_name: filter-ical-frontend-staging
    restart: unless-stopped
    ports:
      - "8001:80"  # Staging on port 8001
    environment:
      - BACKEND_HOST=filter-ical-backend-staging  # Critical: Must match backend container name
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - filter-ical-staging

volumes:
  websites-filter-ical-staging-data:
    external: true

networks:
  filter-ical-staging:
    name: filter-ical-staging
    driver: bridge
