# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class AdminEmail:
        type: str
        value: str
    class AdminPassword:
        type: str
        value: str
    class App:
        name: str
        stage: str
    class FilterIcalApi:
        type: str
        url: str
    class FilterIcalBackendApi:
        name: str
        type: str
    class FilterIcalBackendApiV2:
        name: str
        type: str
    class FilterIcalFrontend:
        type: str
        url: str
    class FilterIcalSyncTask:
        name: str
        type: str
    class FilterIcalSyncTaskV2:
        name: str
        type: str
    class FilterIcalTable:
        name: str
        type: str
    class JwtSecretKey:
        type: str
        value: str

