version: '3.8'

services:
  # Nginx Reverse Proxy - Single entry point for all domains
  nginx:
    image: nginx:alpine
    container_name: websites-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/var/log/nginx
      - letsencrypt-certs:/etc/letsencrypt:ro
      - certbot-webroot:/var/www/certbot:ro
    depends_on:
      - ical-viewer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - websites-network

  # iCal Viewer Frontend - filter-ical.de
  ical-viewer-frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ical-viewer-frontend:latest
    container_name: ical-viewer-frontend
    expose:
      - "80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - websites-network
    labels:
      - "website.domain=filter-ical.de"
      - "website.service=ical-viewer-frontend"

  # iCal Viewer Backend - filter-ical.de  
  ical-viewer:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ical-viewer-backend:latest
    container_name: ical-viewer
    expose:
      - "3000"
    environment:
      - ENV=production
      - PORT=3000
      - DOMAIN=filter-ical.de
    volumes:
      - ical-viewer-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - websites-network
    labels:
      - "website.domain=filter-ical.de"
      - "website.service=ical-viewer"

  # Future: Gabs Massage - gabs-massage.de
  # gabs-massage:
  #   image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gabs-massage:latest
  #   container_name: gabs-massage
  #   expose:
  #     - "4000"
  #   environment:
  #     - ENV=production
  #     - PORT=4000
  #     - DOMAIN=gabs-massage.de
  #   volumes:
  #     - gabs-massage-data:/app/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   networks:
  #     - websites-network
  #   labels:
  #     - "website.domain=gabs-massage.de"
  #     - "website.service=gabs-massage"

  # SSL Certificate Manager
  certbot:
    image: certbot/certbot
    container_name: websites-certbot
    volumes:
      - letsencrypt-certs:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    command: >
      sh -c "
      while :; do 
        sleep 6h & wait $$!; 
        certbot renew --quiet --webroot --webroot-path=/var/www/certbot;
      done
      "
    restart: unless-stopped
    networks:
      - websites-network

networks:
  websites-network:
    driver: bridge
    name: websites-network

volumes:
  # Application data
  ical-viewer-data:
    name: websites-ical-viewer-data
    driver: local
  # gabs-massage-data:
  #   name: websites-gabs-massage-data
  #   driver: local
  
  # Infrastructure
  nginx-logs:
    name: websites-nginx-logs
    driver: local
  letsencrypt-certs:
    name: websites-letsencrypt-certs
    driver: local
  certbot-webroot:
    name: websites-certbot-webroot
    driver: local