"""add calendar_admins table for permissions

Revision ID: 0bda720ee4ad
Revises: 3a51e4bcec06
Create Date: 2025-10-15 10:23:16.403381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bda720ee4ad'
down_revision: Union[str, None] = '3a51e4bcec06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_admins_calendar_id'), 'calendar_admins', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_admins_id'), 'calendar_admins', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_admins_user_id'), 'calendar_admins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_admins_user_id'), table_name='calendar_admins')
    op.drop_index(op.f('ix_calendar_admins_id'), table_name='calendar_admins')
    op.drop_index(op.f('ix_calendar_admins_calendar_id'), table_name='calendar_admins')
    op.drop_table('calendar_admins')
    # ### end Alembic commands ###
