"""add_account_lockout_fields

Revision ID: 11aaba53b3e3
Revises: 87933ac25598
Create Date: 2025-10-08 11:57:39.219875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11aaba53b3e3'
down_revision: Union[str, None] = '87933ac25598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_domain_auth_calendar_id', 'domain_auth', type_='unique')
    op.drop_index('ix_domain_auth_calendar_id', table_name='domain_auth')
    op.create_index(op.f('ix_domain_auth_calendar_id'), 'domain_auth', ['calendar_id'], unique=True)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_domain_auth_calendar_id'), table_name='domain_auth')
    op.create_index('ix_domain_auth_calendar_id', 'domain_auth', ['calendar_id'], unique=False)
    op.create_unique_constraint('uq_domain_auth_calendar_id', 'domain_auth', ['calendar_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
