"""Initial schema with all tables

Revision ID: 25986e61c39d
Revises: 
Create Date: 2025-10-08 11:04:08.286965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25986e61c39d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('footer_visibility', sa.String(), nullable=False),
    sa.Column('show_domain_request', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('domain_key', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendars_id'), 'calendars', ['id'], unique=False)
    op.create_table('domain_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_key', sa.String(length=100), nullable=False),
    sa.Column('admin_password_hash', sa.String(), nullable=True),
    sa.Column('user_password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_auth_domain_key'), 'domain_auth', ['domain_key'], unique=True)
    op.create_index(op.f('ix_domain_auth_id'), 'domain_auth', ['id'], unique=False)
    op.create_table('domain_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_key', sa.String(length=100), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('backup_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_backups_created_at'), 'domain_backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_backups_domain_key'), 'domain_backups', ['domain_key'], unique=False)
    op.create_index(op.f('ix_domain_backups_id'), 'domain_backups', ['id'], unique=False)
    op.create_table('domain_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('requested_domain_key', sa.String(length=100), nullable=False),
    sa.Column('calendar_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('domain_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_requests_created_at'), 'domain_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_requests_domain_key'), 'domain_requests', ['domain_key'], unique=False)
    op.create_index(op.f('ix_domain_requests_email'), 'domain_requests', ['email'], unique=False)
    op.create_index(op.f('ix_domain_requests_id'), 'domain_requests', ['id'], unique=False)
    op.create_index(op.f('ix_domain_requests_requested_domain_key'), 'domain_requests', ['requested_domain_key'], unique=False)
    op.create_index(op.f('ix_domain_requests_status'), 'domain_requests', ['status'], unique=False)
    op.create_index(op.f('ix_domain_requests_username'), 'domain_requests', ['username'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_domain_key'), 'groups', ['domain_key'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('assignment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_key', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_value', sa.String(length=500), nullable=False),
    sa.Column('target_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_rules_domain_key'), 'assignment_rules', ['domain_key'], unique=False)
    op.create_index(op.f('ix_assignment_rules_id'), 'assignment_rules', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('other_ical_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('domain_key', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('subscribed_event_ids', sa.JSON(), nullable=True),
    sa.Column('subscribed_group_ids', sa.JSON(), nullable=True),
    sa.Column('unselected_event_ids', sa.JSON(), nullable=True),
    sa.Column('include_future_events', sa.Boolean(), nullable=True),
    sa.Column('link_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_domain_key'), 'filters', ['domain_key'], unique=False)
    op.create_index(op.f('ix_filters_id'), 'filters', ['id'], unique=False)
    op.create_index(op.f('ix_filters_link_uuid'), 'filters', ['link_uuid'], unique=True)
    op.create_table('recurring_event_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_key', sa.String(length=100), nullable=False),
    sa.Column('recurring_event_title', sa.String(length=500), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_event_groups_domain_key'), 'recurring_event_groups', ['domain_key'], unique=False)
    op.create_index(op.f('ix_recurring_event_groups_id'), 'recurring_event_groups', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_event_groups_recurring_event_title'), 'recurring_event_groups', ['recurring_event_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_event_groups_recurring_event_title'), table_name='recurring_event_groups')
    op.drop_index(op.f('ix_recurring_event_groups_id'), table_name='recurring_event_groups')
    op.drop_index(op.f('ix_recurring_event_groups_domain_key'), table_name='recurring_event_groups')
    op.drop_table('recurring_event_groups')
    op.drop_index(op.f('ix_filters_link_uuid'), table_name='filters')
    op.drop_index(op.f('ix_filters_id'), table_name='filters')
    op.drop_index(op.f('ix_filters_domain_key'), table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_assignment_rules_id'), table_name='assignment_rules')
    op.drop_index(op.f('ix_assignment_rules_domain_key'), table_name='assignment_rules')
    op.drop_table('assignment_rules')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_domain_key'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_domain_requests_username'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_status'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_requested_domain_key'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_id'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_email'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_domain_key'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_created_at'), table_name='domain_requests')
    op.drop_table('domain_requests')
    op.drop_index(op.f('ix_domain_backups_id'), table_name='domain_backups')
    op.drop_index(op.f('ix_domain_backups_domain_key'), table_name='domain_backups')
    op.drop_index(op.f('ix_domain_backups_created_at'), table_name='domain_backups')
    op.drop_table('domain_backups')
    op.drop_index(op.f('ix_domain_auth_id'), table_name='domain_auth')
    op.drop_index(op.f('ix_domain_auth_domain_key'), table_name='domain_auth')
    op.drop_table('domain_auth')
    op.drop_index(op.f('ix_calendars_id'), table_name='calendars')
    op.drop_table('calendars')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
