"""add_unselected_event_ids_to_filters

Revision ID: 291591d9697b
Revises: 85a3a4ab5ad2
Create Date: 2025-10-06 09:33:56.580084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291591d9697b'
down_revision: Union[str, None] = '85a3a4ab5ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unselected_event_ids column to filters table
    op.add_column('filters', sa.Column('unselected_event_ids', sa.JSON(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE filters SET unselected_event_ids = '[]'::json WHERE unselected_event_ids IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unselected_event_ids column from filters table
    op.drop_column('filters', 'unselected_event_ids')
    # ### end Alembic commands ###
