"""add_composite_indexes_for_performance

Revision ID: 3a51e4bcec06
Revises: 1ebb6c1e9f59
Create Date: 2025-10-15 06:42:49.127111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a51e4bcec06'
down_revision: Union[str, None] = '1ebb6c1e9f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
