"""Add domain_auth table for password protection

Revision ID: 5204516d67aa
Revises: fd1683e51aa9
Create Date: 2025-10-02 15:28:00.699074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5204516d67aa'
down_revision: Union[str, None] = 'fd1683e51aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_key', sa.String(length=100), nullable=False),
    sa.Column('admin_password_hash', sa.String(), nullable=True),
    sa.Column('user_password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_auth_domain_key'), 'domain_auth', ['domain_key'], unique=True)
    op.create_index(op.f('ix_domain_auth_id'), 'domain_auth', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_auth_id'), table_name='domain_auth')
    op.drop_index(op.f('ix_domain_auth_domain_key'), table_name='domain_auth')
    op.drop_table('domain_auth')
    # ### end Alembic commands ###
