"""Add email, requested_domain_key, and default_password to DomainRequest

Revision ID: 85a3a4ab5ad2
Revises: 0u62nu8zsa7m
Create Date: 2025-10-02 20:00:28.998515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a3a4ab5ad2'
down_revision: Union[str, None] = '0u62nu8zsa7m'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('domain_requests', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('domain_requests', sa.Column('requested_domain_key', sa.String(length=100), nullable=True))
    op.add_column('domain_requests', sa.Column('default_password', sa.String(length=255), nullable=True))

    # Delete any existing rows (we have no real users yet)
    op.execute('DELETE FROM domain_requests')

    # Now make columns NOT NULL
    op.alter_column('domain_requests', 'email', nullable=False)
    op.alter_column('domain_requests', 'requested_domain_key', nullable=False)
    op.alter_column('domain_requests', 'default_password', nullable=False)

    op.create_index(op.f('ix_domain_requests_email'), 'domain_requests', ['email'], unique=False)
    op.create_index(op.f('ix_domain_requests_requested_domain_key'), 'domain_requests', ['requested_domain_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_requests_requested_domain_key'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_email'), table_name='domain_requests')
    op.drop_column('domain_requests', 'default_password')
    op.drop_column('domain_requests', 'requested_domain_key')
    op.drop_column('domain_requests', 'email')
    # ### end Alembic commands ###
