"""Initial migration - all tables

This is a baseline migration marking the current database schema state.
All tables already exist in the database (created via Base.metadata.create_all).

This migration establishes Alembic version tracking. Future schema changes
will generate proper up/down migrations.

Tables tracked:
- calendars
- events
- groups
- recurring_event_groups
- assignment_rules
- filters
- domain_backups

Revision ID: ad420dcd7f39
Revises:
Create Date: 2025-10-01 08:57:44.609959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad420dcd7f39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
