"""add_domain_ownership_and_user_relationships

Revision ID: b4c9e444b42e
Revises: 7add62adc884
Create Date: 2025-10-09 09:45:57.108090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c9e444b42e'
down_revision: Union[str, None] = '7add62adc884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'domain_id')
    )
    op.add_column('domain_requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_domain_requests_user_id'), 'domain_requests', ['user_id'], unique=False)
    op.create_foreign_key(None, 'domain_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('domains', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('domains_calendar_id_key', 'domains', type_='unique')
    op.drop_constraint('domains_domain_key_key', 'domains', type_='unique')
    op.drop_index('ix_domains_calendar_id', table_name='domains')
    op.create_index(op.f('ix_domains_calendar_id'), 'domains', ['calendar_id'], unique=True)
    op.drop_index('ix_domains_domain_key', table_name='domains')
    op.create_index(op.f('ix_domains_domain_key'), 'domains', ['domain_key'], unique=True)
    op.create_index(op.f('ix_domains_owner_id'), 'domains', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'domains', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domains', type_='foreignkey')
    op.drop_index(op.f('ix_domains_owner_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_domain_key'), table_name='domains')
    op.create_index('ix_domains_domain_key', 'domains', ['domain_key'], unique=False)
    op.drop_index(op.f('ix_domains_calendar_id'), table_name='domains')
    op.create_index('ix_domains_calendar_id', 'domains', ['calendar_id'], unique=False)
    op.create_unique_constraint('domains_domain_key_key', 'domains', ['domain_key'])
    op.create_unique_constraint('domains_calendar_id_key', 'domains', ['calendar_id'])
    op.drop_column('domains', 'owner_id')
    op.drop_constraint(None, 'domain_requests', type_='foreignkey')
    op.drop_index(op.f('ix_domain_requests_user_id'), table_name='domain_requests')
    op.drop_column('domain_requests', 'user_id')
    op.drop_table('domain_admins')
    # ### end Alembic commands ###
