"""Add filtered calendar cache fields for real-time iCal updates

Revision ID: f6fa43af57c3
Revises: 
Create Date: 2025-09-18 19:23:24.869716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f6fa43af57c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filtered_calendars', sa.Column('cached_ical_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('filtered_calendars', sa.Column('cached_content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('filtered_calendars', sa.Column('cache_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filtered_calendars', 'cache_updated_at')
    op.drop_column('filtered_calendars', 'cached_content_hash')
    op.drop_column('filtered_calendars', 'cached_ical_content')
    # ### end Alembic commands ###
