"""Add domain_requests table

Revision ID: fd1683e51aa9
Revises: ed716677d1fb
Create Date: 2025-10-01 11:58:03.259608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1683e51aa9'
down_revision: Union[str, None] = 'ed716677d1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('calendar_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('domain_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_requests_created_at'), 'domain_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_requests_domain_key'), 'domain_requests', ['domain_key'], unique=False)
    op.create_index(op.f('ix_domain_requests_id'), 'domain_requests', ['id'], unique=False)
    op.create_index(op.f('ix_domain_requests_status'), 'domain_requests', ['status'], unique=False)
    op.create_index(op.f('ix_domain_requests_username'), 'domain_requests', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_requests_username'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_status'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_id'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_domain_key'), table_name='domain_requests')
    op.drop_index(op.f('ix_domain_requests_created_at'), table_name='domain_requests')
    op.drop_table('domain_requests')
    # ### end Alembic commands ###
