name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: duersjefen/filter-ical-backend
  IMAGE_NAME_FRONTEND: duersjefen/filter-ical-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

      - name: 📢 Image tags
        run: |
          echo "Backend images:"
          echo "${{ steps.meta-backend.outputs.tags }}"
          echo ""
          echo "Frontend images:"
          echo "${{ steps.meta-frontend.outputs.tags }}"
          echo ""
          echo "✅ Images pushed to GitHub Container Registry"

      - name: 🚀 Notify platform repo to deploy
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.PLATFORM_DEPLOY_TOKEN }}
        run: |
          echo "📢 Notifying platform repo of new images..."
          gh api repos/duersjefen/multi-tenant-platform/dispatches \
            -f event_type="new-image" \
            -f client_payload[project]="filter-ical" \
            -f client_payload[sha]="${{ github.sha }}" \
            -f client_payload[actor]="${{ github.actor }}" \
            -f client_payload[backend_tag]="latest" \
            -f client_payload[frontend_tag]="latest"
          echo "✅ Platform will deploy to staging automatically"
          echo "👀 Monitor: https://github.com/duersjefen/multi-tenant-platform/actions"