name: Emergency Server Restart

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "RESTART" to confirm'
        required: true

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  restart:
    if: github.event.inputs.confirm == 'RESTART'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        env:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCOUNT_ID,AWS_REGION,ECR_REGISTRY
          script: |
            cd /opt/websites
            echo "🔍 Current container status:"
            docker ps -a | grep -E "nginx|filter-ical"

            echo "🔄 Restarting all services..."
            export AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID}"
            export AWS_REGION="${AWS_REGION}"
            export ECR_REGISTRY="${ECR_REGISTRY}"

            docker-compose down
            docker-compose up -d

            echo "⏳ Waiting for services to start..."
            sleep 15

            echo "🔍 New container status:"
            docker ps

            echo "🧪 Testing nginx config:"
            docker exec websites-nginx nginx -t

            echo "✅ Restart completed!"