name: Extend EBS Filesystem

on:
  workflow_dispatch:

jobs:
  extend-filesystem:
    name: Extend Filesystem to Use Full Disk Space
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: 🔧 Extend Filesystem on EC2 Instance
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "🔍 Current disk usage:"
          df -h /
          echo ""

          echo "🔍 Block devices:"
          lsblk
          echo ""

          # Detect root device
          ROOT_DEVICE=$(df / | tail -1 | awk '{print $1}')
          echo "📍 Root filesystem device: $ROOT_DEVICE"

          # Extract device and partition info
          if [[ $ROOT_DEVICE == /dev/nvme* ]]; then
            # NVMe device (e.g., /dev/nvme0n1p1)
            DEVICE=$(echo $ROOT_DEVICE | sed 's/p[0-9]*$//')
            PARTITION=$(echo $ROOT_DEVICE | sed 's/.*p//')
          else
            # Standard device (e.g., /dev/xvda1)
            DEVICE=$(echo $ROOT_DEVICE | sed 's/[0-9]*$//')
            PARTITION=$(echo $ROOT_DEVICE | sed 's/.*[^0-9]//')
          fi

          echo "💾 Device: $DEVICE"
          echo "📂 Partition: $PARTITION"
          echo ""

          echo "🔧 Extending partition..."
          sudo growpart $DEVICE $PARTITION || {
            echo "⚠️  Partition already at maximum size or growpart failed"
          }
          echo ""

          # Detect filesystem type
          FS_TYPE=$(df -T / | tail -1 | awk '{print $2}')
          echo "📁 Filesystem type: $FS_TYPE"
          echo ""

          echo "🔧 Resizing filesystem..."
          if [[ $FS_TYPE == "ext"* ]]; then
            sudo resize2fs $ROOT_DEVICE
          elif [[ $FS_TYPE == "xfs" ]]; then
            sudo xfs_growfs /
          else
            echo "❌ Unsupported filesystem type: $FS_TYPE"
            exit 1
          fi
          echo ""

          echo "✅ Filesystem extended successfully!"
          echo ""
          echo "🔍 New disk usage:"
          df -h /